title: Klaus Eduard's Projects
description: An index of software projects and experiments
webmaster_verifications:
  google: REPLACE_WITH_YOUR_GOOGLE_VERIFICATION_CODE

# Theme settings
theme: jekyll-theme-minimal
show_downloads: false 